In [60]:
import numpy as np 


In [61]:
pattern = np.load('data/pattern.npy')
node_num = np.load('data/node_num.npy')
link_num = np.load('data/link_num.npy')
pressure = np.load('data/pressure.npy')
flow = np.load('data/flow.npy')

In [62]:
print(pattern)
print(type(pattern))
print(pattern.shape)
print(pattern[0])
print(pattern[0].shape)

[[4.824115   1.32191011 4.41476974 ... 3.35491382 2.96865897 4.00999223]
 [4.66643724 3.1101346  0.20475493 ... 2.71819088 4.71450213 3.2337881 ]
 [3.1259722  4.14071378 2.64921332 ... 2.74249623 4.45950743 3.78760727]
 ...
 [0.48652389 1.79028981 1.87811366 ... 1.78536609 0.34801814 0.80283645]
 [0.38253275 0.8659268  1.14623531 ... 3.40407136 3.65401033 1.37798745]
 [2.75732496 0.38738804 1.1083414  ... 2.86274237 2.68779958 4.62177384]]
<class 'numpy.ndarray'>
(30000, 24)
[4.824115   1.32191011 4.41476974 1.65745072 2.1112283  3.00090793
 1.21908491 4.73199919 0.98845602 4.87696905 1.46960271 4.82837605
 1.80823612 3.88906738 3.28789198 0.1372677  3.12488346 2.74301768
 3.36282582 0.24439316 2.21138705 3.35491382 2.96865897 4.00999223]
(24,)


In [63]:
print(node_num)
print(type(node_num))
print(node_num.shape)

[ 10 101 103 105 107 109 111 113 115 117 119 120 121 123 125 127 129 131
 139 141 143 145 147 149  15 151 153 157 159 161 163 164 166 167 169 171
 173 177 179 181 183 184 185 187 189 191 193 195 197 199  20 201 203 204
 205 206 207 208 209 211 213 215 217 219 225 229 231 237 239 241 243 247
 249 251 253 255 257 259 261 263 265 267 269 271 273 275  35  40  50  60
 601  61]
<class 'numpy.ndarray'>
(92,)


In [64]:
print(link_num)
print(type(link_num))
print(link_num.shape)

[ 20  40  50  60 101 103 105 107 109 111 112 113 114 115 116 117 119 120
 121 122 123 125 129 131 133 135 137 145 147 149 151 153 155 159 161 163
 169 171 173 175 177 179 180 181 183 185 186 187 189 191 193 195 197 199
 201 202 203 204 205 207 209 211 213 215 217 219 221 223 225 229 231 233
 235 237 238 239 240 241 243 245 247 249 251 257 261 263 269 271 273 275
 277 281 283 285 287 289 291 293 295 297 299 301 303 305 307 309 311 313
 315 317 319 321 323 325 329 330 333]
<class 'numpy.ndarray'>
(117,)


In [65]:
print(pressure)
# print(type(pressure))
print(pressure.shape)
# print(pressure[29999][91])
# print(pressure[0].shape)


[[[-22.62  40.68  37.14 ...  -6.5  -14.18 -22.29]
  [ 22.88  58.35  46.88 ...  39.    31.32  23.21]
  [ 22.44  56.84  44.97 ...  38.56  30.88  22.77]
  ...
  [ 90.4   90.62  90.5  ...  90.63  90.57  90.46]
  [129.99 131.44 130.61 ... 131.47 131.07 130.37]
  [129.99 131.44 130.61 ... 131.47 131.07 130.37]]

 [[-21.07  38.45  42.51 ... -19.89  -8.77 -20.78]
  [ 24.43  51.13  64.23 ...  25.6   36.73  24.72]
  [ 23.99  49.38  62.88 ...  25.16  36.29  24.28]
  ...
  [ 90.42  90.51  90.75 ...  90.53  90.59  90.47]
  [130.08 130.67 132.32 ... 130.82 131.25 130.46]
  [130.08 130.67 132.32 ... 130.82 131.25 130.46]]

 [[ -8.93  37.43  39.03 ... -18.44 -13.56  -9.55]
  [ 36.57  47.8   52.99 ...  27.06  31.93  35.95]
  [ 36.13  45.92  51.29 ...  26.62  31.49  35.51]
  ...
  [ 90.5   90.5   90.54 ...  90.51  90.53  90.53]
  [130.61 130.61 130.9  ... 130.68 130.79 130.83]
  [130.61 130.61 130.9  ... 130.68 130.79 130.83]]

 ...

 [[  2.6   40.44  40.44 ...   3.88   2.45   4.29]
  [ 48.09  57.55  57

In [66]:
print(flow)
print(type(flow))
print(flow.shape)
print(flow[1][116])
print(flow[0].shape)

[[[ 3696.84 -3771.43   641.71 ...   964.94  2863.4   4434.55]
  [ 2479.57 -1525.3   1265.81 ...  1081.42  1732.48  2230.27]
  [ 1830.11  -246.64  1295.6  ...   440.75   981.65  1426.74]
  ...
  [13395.25 13071.15 13257.2  ... 13063.93 13155.04 13310.21]
  [    0.       0.       0.   ...     0.       0.       0.  ]
  [   -0.      -0.      -0.   ...    -0.      -0.      -0.  ]]

 [[ 3407.87 -1380.49 -5327.77 ...  3956.46  1514.48  4151.01]
  [ 2375.34    13.7  -2234.1  ...  2306.78  1167.36  2129.29]
  [ 1764.31   788.3   -924.85 ...  1400.16   570.91  1349.88]
  ...
  [13373.63 13244.17 12875.79 ... 13209.17 13113.85 13290.97]
  [    0.       0.       0.   ...     0.       0.       0.  ]
  [   -0.      -0.      -0.   ...    -0.      -0.      -0.  ]]

 [[  418.1    142.65 -1722.65 ...  3529.92  2464.7   1600.97]
  [ 1413.91  1026.88  -615.98 ...  2019.44  1438.33   787.65]
  [ 1137.02  1244.19   478.81 ...  1305.29   935.82   630.02]
  ...
  [13256.62 13256.09 13191.53 ... 13240.66 13215

In [67]:
import random
num_samples = 30000
num_train = int(0.6 * num_samples)
num_validation = int(0.2 * num_samples)
num_test = int(0.2 * num_samples)

randid = random.sample(range(0, num_samples), num_samples)
train_id = randid[0:num_train]
validation_id = randid[num_train:num_validation+num_train]
test_id = randid[num_validation+num_train:num_samples]
# print(randid)
# print(train_id)
# print(validation_id)
# print(test_id)


In [68]:
train_pressure = pressure[train_id]
train_flow = flow[train_id]
train_pattern = pattern[train_id]

validation_pressure = pressure[validation_id]
validation_flow = flow[validation_id]
validation_pattern = pattern[validation_id]

test_pressure = pressure[test_id]
test_flow = flow[test_id]
test_pattern = pattern[test_id]
print(train_pressure[18000-1,0])

[  1.22  42.34  42.11  38.48  38.56  37.85  37.97  38.02  38.73  38.65
  40.21  38.59  37.31  39.07  39.51   1.1   -0.36  -7.9   -4.23 -16.49
  -1.75  -3.02  -5.41  -4.22   1.43]


In [78]:
import torch
import torch.nn as nn
from sklearn import preprocessing

n_feature = 92+117

train_data = np.zeros((18000,n_feature,24))
# tmp = np.zeros((18000,n_feature,24))
print(train_pressure.shape)
print(train_flow.shape)

train_data[:,0:92,0:24] = train_pressure[:,:,1:25]
train_data[:,92:n_feature,0:24] = train_flow[:,:,1:25]


for i in range(num_train):
    print(i)
    for j in range(n_feature):
    #     print(i,j)
        
        train_data[i][j] = preprocessing.scale(train_data[i][j])
    # train_data[i][0:92] = preprocessing.scale(train_data[i][0:92])
    # train_data[i][92:92+117] = preprocessing.scale(train_data[i][92:92+117])


train_value = train_pattern[:,23]

train_data = np.array(train_data)
train_data = torch.tensor(train_data)
train_data = train_data.to(torch.float32)
print(train_data.shape)


        

print(train_data.shape)
train_value = np.array(train_value).flatten()
train_value = torch.tensor(train_value)
print(train_value.shape)
print(train_data[1:100])

(18000, 92, 25)
(18000, 117, 25)
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107


KeyboardInterrupt: 

In [75]:


class CNN(nn.Module):
    def __init__(self):
        super(CNN, self).__init__()
        self.conv1 = nn.Sequential(  # input shape (1, 209, 23)
            nn.Conv2d(
                in_channels=1,      # input height
                out_channels=16,    # n_filters
                kernel_size=(1,3),      # filter size
                stride=1,           # filter movement/step
                padding=(0,1),      # 如果想要 con2d 出来的图片长宽没有变化, padding=(kernel_size-1)/2 当 stride=1
            ),      # output shape (16, 209, 23)
            nn.ReLU(),    # activation
            nn.MaxPool2d((1,3),(1,2), (0,1)),    # 在 2x2 空间里向下采样, output shape (16, 104, 11)
        )
        self.conv2 = nn.Sequential(  # input shape (16, 104, 11)
            nn.Conv2d(16, 32, (1,3), 1, (0,1)),  # output shape (32, 104, 11)
            nn.ReLU(),  # activation
            nn.MaxPool2d((1,3),(1,2), (0,1)),    # 在 2x2 空间里向下采样, output shape (16, 104, 11)
        )
        self.conv3 = nn.Sequential(  # input shape (16, 104, 11)
            nn.Conv2d(32, 64, (1,3), 1, (0,1)),  # output shape (32, 104, 11)
            nn.ReLU(),  # activation
            nn.MaxPool2d((1,4),(1,2), (0,0)),    # 在 2x2 空间里向下采样, output shape (16, 104, 11)
        )
        self.out = nn.Linear(64 * 209 * 2, 1)   # fully connected layer, output 10 classes

    # def forward(self, x):
    #     print(x.shape)
    #     x = self.conv1(x)
    #     print(x.shape)
    #     x = self.conv2(x)
    #     print(x.shape)
    #     x = self.conv3(x)
    #     print(x.shape)
    #     x = x.view(x.size(0), -1)   # 展平多维的卷积图成 (batch_size, 32 * 7 * 7)
    #     print(x.shape)
    #     output = self.out(x)
    #     print(output.shape)
    #     return output,x
    def forward(self, x):
        # print(x.shape)
        x = self.conv1(x)
        # print(x.shape)
        x = self.conv2(x)
        # print(x.shape)
        x = self.conv3(x)
        # print(x.shape)
        x = x.view(x.size(0), -1)   # 展平多维的卷积图成 (batch_size, 32 * 7 * 7)
        # print(x.shape)
        output = self.out(x)
        # print(output.shape)
        return output,x

cnn = CNN()
print(cnn)  # net architecture

CNN(
  (conv1): Sequential(
    (0): Conv2d(1, 16, kernel_size=(1, 3), stride=(1, 1), padding=(0, 1))
    (1): ReLU()
    (2): MaxPool2d(kernel_size=(1, 3), stride=(1, 2), padding=(0, 1), dilation=1, ceil_mode=False)
  )
  (conv2): Sequential(
    (0): Conv2d(16, 32, kernel_size=(1, 3), stride=(1, 1), padding=(0, 1))
    (1): ReLU()
    (2): MaxPool2d(kernel_size=(1, 3), stride=(1, 2), padding=(0, 1), dilation=1, ceil_mode=False)
  )
  (conv3): Sequential(
    (0): Conv2d(32, 64, kernel_size=(1, 3), stride=(1, 1), padding=(0, 1))
    (1): ReLU()
    (2): MaxPool2d(kernel_size=(1, 4), stride=(1, 2), padding=(0, 0), dilation=1, ceil_mode=False)
  )
  (out): Linear(in_features=26752, out_features=1, bias=True)
)


In [76]:
# import torch
# import torch.nn.functional as F
# from sklearn.preprocessing import LabelEncoder
import torch.utils.data as Data
from sklearn.metrics import mean_squared_error
# optimizer is a tool used for training
optimizer  = torch.optim.Adam(cnn.parameters(), lr=0.005, betas=(0.9, 0.99))
# when calculating errors, it is noted that the real value is not one-hot, but 1D tensor (batch,)
# but the predicted value is 2D tensor (batch, n_ classes)
loss_func = torch.nn.MSELoss()

torch.manual_seed(1)    # reproducible
BATCH_SIZE = 32      # number of batch training data
# first, convert it into a dataset recognized by torch
torch_dataset = Data.TensorDataset(train_data,train_value)
# put the dataset into the dataloader
loader = Data.DataLoader(
    dataset=torch_dataset,      # torch TensorDataset format
    batch_size=BATCH_SIZE,      # mini batch size
    shuffle=False,               # do you want to scramble the data,yes
    num_workers=2,              # multithreading to read data
)

for epoch in range(8):
    for step,data in enumerate(loader):
        batch_x,batch_y = data[0][:].type(torch.float), data[1][:].type(torch.float)
        # if step == 0:
        #     print(batch_x)
        #     print(batch_y)
        batch_x = batch_x[:, None, ...]
        # print(type(batch_x))
        # print(batch_y.shape)
        out = cnn(batch_x)[0]     # feed net training data x, output analysis value
        # print(batch_y.shape)

        loss = loss_func(out, batch_y)     # calculate the error between the two
        # print(loss)

        optimizer.zero_grad()   # clear the residual update parameter value of the previous step
        loss.backward()         # the error is back propagated and the updated values of parameters are calculated
        optimizer.step()        # apply the parameter update value to the parameters of net
        if epoch % 1 == 0 and step == 0:
            # prediction = torch.max(out, 1)[1]
            pred_y = out.data.numpy()[:,0]
            target_y = batch_y.data.numpy()
            # print(pred_y)
            # print(target_y)
            sum = 0
            for i in range(BATCH_SIZE):
                sum = sum + abs(((pred_y[i]-target_y[i])/target_y[i]))
            metric = sum / BATCH_SIZE
            # print(pred_y)
            # print(target_y)
            # mse = mean_squared_error(target_y, pred_y)
            # # accuracy = float( (pred_y == target_y).astype(int).sum()) / float(target_y.size)
            print('Epoch:',epoch,'| metric: %.2f' % metric)


# torch.save(net.state_dict(), 'net_params.pkl')   # only save the parameters in the network (fast, less memory)

# validation_net = torch.nn.Sequential(
#     torch.nn.Linear(n_feature, 100),
#     torch.nn.ReLU(),
#     torch.nn.Linear(100, 100),
#     torch.nn.ReLU(),
#     torch.nn.Linear(100, 100),
#     torch.nn.ReLU(),
#     torch.nn.Linear(100, 100),
#     torch.nn.ReLU(),
#     torch.nn.Linear(100, 100),
#     torch.nn.ReLU(),
#     torch.nn.Linear(100, 1),
# )
# # copy saved parameters to predict_net
# validation_net.load_state_dict(torch.load('net_params.pkl'),False)
# prediction = validation_net(test_data_aft_stdsscsl)
# prediction = torch.max(prediction, 1)[1]
# pred_y = prediction.data.numpy()
# target_y = test_label.data.numpy()
# real_pred_y = le.inverse_transform(pred_y)
# print("predicted label: ",real_pred_y)
# accuracy = float((pred_y == target_y).astype(int).sum()) / float(target_y.size)
# print("Accuracy on test set: ",accuracy*100,"%")
# np.savetxt("predict_testlabel_with_adjlist.txt",real_pred_y)

Epoch: 0 | metric: 0.98
Epoch: 1 | metric: 2.66
Epoch: 2 | metric: 2.62
Epoch: 3 | metric: 2.61
Epoch: 4 | metric: 2.60
Epoch: 5 | metric: 2.59
Epoch: 6 | metric: 2.58
Epoch: 7 | metric: 2.58


In [51]:
print(target_y.mean())

2.527834


In [52]:
a = np.zeros((3,3))
print(a)
a[0][1] = 2
print(a[0][0:3])

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[0. 2. 0.]
